# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(764, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.pointShapefileInputTB = QtWidgets.QToolButton(self.groupBox)
        self.pointShapefileInputTB.setObjectName("pointShapefileInputTB")
        self.gridLayout.addWidget(self.pointShapefileInputTB, 1, 2, 1, 1)
        self.countryShapefileInputTB = QtWidgets.QToolButton(self.groupBox)
        self.countryShapefileInputTB.setObjectName("countryShapefileInputTB")
        self.gridLayout.addWidget(self.countryShapefileInputTB, 0, 2, 1, 1)
        self.countryShapefileInput = QtWidgets.QLineEdit(self.groupBox)
        self.countryShapefileInput.setObjectName("countryShapefileInput")
        self.gridLayout.addWidget(self.countryShapefileInput, 0, 1, 1, 1)
        self.pointShapefileInput = QtWidgets.QLineEdit(self.groupBox)
        self.pointShapefileInput.setObjectName("pointShapefileInput")
        self.gridLayout.addWidget(self.pointShapefileInput, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.countryNameLE = QtWidgets.QLineEdit(self.groupBox_2)
        self.countryNameLE.setObjectName("countryNameLE")
        self.horizontalLayout_2.addWidget(self.countryNameLE)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 7, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 3, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_2.addWidget(self.comboBox, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.certainShopsComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.certainShopsComboBox.setObjectName("certainShopsComboBox")
        self.gridLayout_2.addWidget(self.certainShopsComboBox, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.outputShapefileTB = QtWidgets.QToolButton(self.groupBox_3)
        self.outputShapefileTB.setObjectName("outputShapefileTB")
        self.gridLayout_3.addWidget(self.outputShapefileTB, 0, 2, 1, 1)
        self.outputShapefileLE = QtWidgets.QLineEdit(self.groupBox_3)
        self.outputShapefileLE.setObjectName("outputShapefileLE")
        self.gridLayout_3.addWidget(self.outputShapefileLE, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.startPB = QtWidgets.QPushButton(self.centralwidget)
        self.startPB.setObjectName("startPB")
        self.horizontalLayout.addWidget(self.startPB)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Feature Extractor"))
        self.groupBox.setToolTip(_translate("MainWindow", "Specify paths for the input datasets."))
        self.groupBox.setTitle(_translate("MainWindow", "Input Data"))
        self.pointShapefileInputTB.setText(_translate("MainWindow", "..."))
        self.countryShapefileInputTB.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "Country shapefile:"))
        self.label.setText(_translate("MainWindow", "Point shapefile:"))
        self.groupBox_2.setToolTip(_translate("MainWindow", "Provide the name of the Central American country you would like to extract features for. You MUST hit enter when you\'re done entering the name."))
        self.groupBox_2.setTitle(_translate("MainWindow", "Target Country"))
        self.label_3.setText(_translate("MainWindow", "Country Name:"))
        self.groupBox_4.setToolTip(_translate("MainWindow", "Choose whether you would like to extract all shops in your country of interest or only shops of a specific type. If you only want to extract shops of a specfic type, choose the type you are interested from the drop-down list. Once you have made your selections, click the \"Update Extraction Options\" button."))
        self.groupBox_4.setTitle(_translate("MainWindow", "Shops"))
        self.pushButton.setText(_translate("MainWindow", "Update Extraction Options"))
        self.label_6.setText(_translate("MainWindow", "If only extracting a certain type, choose type of shop to extract:"))
        self.label_4.setText(_translate("MainWindow", "Please choose if you would like to extract all shops or only shops of a specific type:"))
        self.groupBox_3.setToolTip(_translate("MainWindow", "Specify the path where you would like the output shapefile to be written."))
        self.groupBox_3.setTitle(_translate("MainWindow", "Output"))
        self.label_7.setText(_translate("MainWindow", "Output shapefile path:"))
        self.outputShapefileTB.setText(_translate("MainWindow", "..."))
        self.startPB.setText(_translate("MainWindow", "Start Feature Extraction"))

